INSERT INTO USUARIO  (ID,NOME,EMAIL,SENHA) VALUES (1,'Cristiano rodriges Borges', 'crrborges@gmail.com', '$2a$10$BAEONZtNWlfAtiS5Xtc/gOES//SlBtLOBRrT.Txg4ltnZQgwzBaOW');
INSERT INTO USUARIO  (ID,NOME,EMAIL,SENHA) VALUES (2,'Luis inacio', 'lula@gmail.com', '$2a$10$BAEONZtNWlfAtiS5Xtc/gOES//SlBtLOBRrT.Txg4ltnZQgwzBaOW');

INSERT INTO ROLE  (ID,NOME) VALUES (1,'ROLE_OPERADOR');
INSERT INTO ROLE  (ID,NOME) VALUES (2,'ROLE_ADMINISTRADOR');

INSERT INTO USUARIO_ROLE   (ID_USUARIO , ID_ROLE ) VALUES (1, 1);
INSERT INTO USUARIO_ROLE   (ID_USUARIO , ID_ROLE ) VALUES (2, 1);
INSERT INTO USUARIO_ROLE   (ID_USUARIO , ID_ROLE ) VALUES (2, 2);
